CREATE DATABASE [Chicago_taxis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Chicago_taxis', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL22\MSSQL\DATA\Chicago_taxis.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Chicago_taxis_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL22\MSSQL\DATA\Chicago_taxis_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [Chicago_taxis] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Chicago_taxis] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Chicago_taxis] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Chicago_taxis] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Chicago_taxis] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Chicago_taxis] SET ARITHABORT OFF 
GO
ALTER DATABASE [Chicago_taxis] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Chicago_taxis] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Chicago_taxis] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Chicago_taxis] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Chicago_taxis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Chicago_taxis] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Chicago_taxis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Chicago_taxis] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Chicago_taxis] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Chicago_taxis] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Chicago_taxis] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Chicago_taxis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Chicago_taxis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Chicago_taxis] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Chicago_taxis] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Chicago_taxis] SET  READ_WRITE 
GO
ALTER DATABASE [Chicago_taxis] SET RECOVERY FULL 
GO
ALTER DATABASE [Chicago_taxis] SET  MULTI_USER 
GO
ALTER DATABASE [Chicago_taxis] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Chicago_taxis] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Chicago_taxis] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Chicago_taxis]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Chicago_taxis]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Chicago_taxis] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO